<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Home</title>
        <meta charset="utf-8">
        <?php Tag::css('reset'); ?>
        <?php Tag::css('layout'); ?>
        <?php Tag::css('style'); ?>
        <?php Tag::js('jquery/jquery.min', -100) ?>
        <?php Tag::js('cufon-yui') ?>
        <?php Tag::js('cufon-replace') ?>
        <?php Tag::js('UkrainianMysl_400.font') ?>
        <?php Tag::js('HomewardBound_400.font') ?>
    <!--NOTICIAS PLUGINS-->
        <?php Tag::js('jquery.timer'); ?>
        <?php Tag::js('jquery.easing.1.3'); ?>
        <?php Tag::js('jquery.dwdinanews.0.1'); ?>
        <?php Tag::js('news') ?>
    <!--END NOTICIAS PLUGINS-->

        <!--[if lt IE 9]>
        <script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
        <?php Tag::js('html5') ?>
        <![endif]-->
        <?php echo Html::includeCss() ?>
        <?php echo Html::includeJs() ?>
    </head>
    <body id="page1">
        <div class="main">
            <!-- header -->
            <?php KumbiaPHP\View\View::partial('header') ?>
            <!-- / header -->
            <!--content -->
            <section id="content">
                <article class="col1">
                    <div class="box1 min_height">                        
                        <?php KumbiaPHP\View\View::content() ?>
                    </div>
                </article>
                <article class="col2 pad_left1">
                    <?php if (!KumbiaPHP\View\View::get('security')->isLogged()): ?>
                        <?php KumbiaPHP\View\View::partial('inicio_sesion') ?>
                    <?php endif; ?>
                        <?php KumbiaPHP\View\View::partial('barra_derecha') ?>
                </article>
            </section>
            <!-- / content -->
            <!-- footer -->
            <?php KumbiaPHP\View\View::partial('footer') ?>
            <!-- / footer -->
        </div>
        <script type="text/javascript"> Cufon.now(); </script>
    </body>
</html>