<?php

use KumbiaPHP\View\View;

/*
 * Partial que genera los mensajes flash en formato html
 */

if (0 === count($messages = (array) View::flash()->getAll())) {
    return;
}
?>
<br/>
<div class="messages-flash">
    <?php foreach ($messages as $type => $messages): ?>
        <?php foreach ((array) $messages as $message): ?>
            <div class="flash <?php echo $type ?>"><?php echo $message ?></div>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>
