
<?php Tag::js('chat', 200) ?>

<style>
    #chatbox {
        border: 1px solid #666666;
        border-radius: 10px 10px 10px 10px;
        height: 398px;
        margin: 10px -15px 0;
        overflow-y: scroll;
        padding: 10px;
        width: 638px;
    }
    #chatinput {
        height: 75px;
        margin-left: -15px;
        width: 641px;
        resize: none;
    }
</style>

<div id="chatbox">
    <?php foreach ($mensajes as $value) : ?>

        <p>
        <table>
            <tr>
                <td rowspan="2">
                    <?php echo Html::img($value['imagen'], 'Foto de ' . $value['nombre'], array('width' => '40px', 'height' => '48px')) ?>
                </td>
                <td style=" padding-left: 7px">
            <b><?php echo $value['nombre'] . ' dice:' ?></b>
                </td>
            </tr>
            <tr>
            <td style=" padding-left: 7px">
            <?php echo $value['mensaje'] ?>
            </td>
            </tr>
        </table>
    </p>

<?php endforeach; ?>
</div>
<div>
    <?php echo Form::open('chat/enviar_mensaje', 'post', array('id' => 'chatform')) ?>
    <?php echo Form::hidden('ultimo_id', null, $ultimo_id) ?>
    <textarea id="chatinput" name="mensaje"></textarea>
    <?php echo Form::close() ?>
</div>
