<?php \KumbiaPHP\View\View::content(true) ?>
<?php $form['regalo_esperado']['style'] = 'width:345px; height:140px;padding:5px;text-decoration:' ?>
<?php echo $form->open(array('class' => 'form')) ?>
<div style='margin-top:50px;'>
    <label style="display:inline-block;margin-top:60px;font-size:16px;">
        <?php echo $form['regalo_esperado']['label'] ?>
    </label>
    <?php echo $form['regalo_esperado'] ?>
    <input type="submit" value="Guardar Regalo" class="button" style='float:right;margin-right:5px;'; />
</div>
<?php echo $form->close() ?>