<table>
    <tr>
        <td>
            Los regalos son de un monto mínimo de 500 Bs. más lo que toque por el almuerzo.
            monto que considero realmente tonto tomando en cuenta que el viernes 14-12 debemos cobrar al menos 15 mir bolivares cada uno en utilidades...
            El Melón!!!
            </br></br></br>
            work in progresssss!!!
        </td>
        <td>
            <?php echo Html::img('trabajadores-flojos.jpg'); ?>
        </td>
    </tr>
</table>