<div style="font-weight:bold;font-size:18px;font-family:tahoma;padding:7px;margin-bottom:10px;text-align:center;">
    Querido Super Amigo Secreto Quiero que me Regales...
</div>
<div style="clear: both;"></div>
<table style="width:100%;">
    <tbody>
    <?php $i = 0; foreach ($usuarios as $usu) { ?>
    <tr>
        <td style="width:90px">
            <div style="margin:0 0 10px 10px;"><?php echo Html::img($usu->imagen, '', 'width="100%" title="' . $usu->personaje . '"'); ?></div>
        </td>
        <td>
            <div style="margin-left:10px;margin-top:40px;float:left;font-weight:bold;">Deseo:</div>
            <?php if ($usu->regalo_esperado == "") { ?>
                <div style="border-style: solid;border-width:1px;border-color:#808080;background-color:#f6f6f6;
                        margin:0px 0px 0 10px;float:left;font-weight:bold;font-size:15px;color:red;
                        width:460px;height:85px;text-align:justify;padding: 5px;">
                    <div style="margin-left:30px;margin-top:40px;float:left;color:red;font-weight: bold;">Un</div>
                    <div style="margin:20px 0 0 5px;float:left;"><?php echo Html::img('banana.gif', '', 'width="60"'); ?></div>
                    <div style="margin-left:10px;margin-top:40px;float:left;color:red;font-weight: bold;"> Bien grande...</div>
                </div>
            <?php } else { ?>
                <div style="border-style: solid;border-width:1px;border-color:#808080;background-color:#f6f6f6;
                    margin:0px 0px 0 10px;float:left;font-weight:bold;font-size:15px;color:red;
                    width:460px;height:85px;text-align:justify;padding: 5px;">
                        <?php echo $usu->regalo_esperado; ?>
                </div>
            <?php } ?>
        </td>
    </tr>
    <?php } ?>
    </tbody>
</table>