<?php \KumbiaPHP\View\View::content(true) ?>
<?php echo $form->open() ?>
<dl>
    <?php if (isset($form['clave_actual'])): ?>
        <dd><label><?php echo $form['clave_actual']['label'] ?></label></dd>
        <dt><?php echo $form['clave_actual'] ?></dt>
    <?php endif; ?>
    <dd><label><?php echo $form['nueva_clave']['label'] ?></label></dd>
    <dt><?php echo $form['nueva_clave'] ?></dt>
    <dd><label><?php echo $form['nueva_clave2']['label'] ?></label></dd>
    <dt><?php echo $form['nueva_clave2'] ?></dt>
</dl>
<input type="submit" value="Guardar" />
<?php echo $form->close() ?>