<?php \KumbiaPHP\View\View::content(true) ?>
<?php echo $form->open(array('class' =>'form')) ?>
<dl>
    <dd><label><?php echo $form['correo']['label'] ?></label></dd>
    <dt><?php echo $form['correo'] ?></dt>
    <?php if (isset($form['clave_actual'])): ?>
        <dd><label><?php echo $form['clave_actual']['label'] ?></label></dd>
        <dt><?php echo $form['clave_actual'] ?></dt>
    <?php endif; ?>
    <dd><label><?php echo $form['nueva_clave']['label'] ?></label></dd>
    <dt><?php echo $form['nueva_clave'] ?></dt>
    <dd><label><?php echo $form['nueva_clave2']['label'] ?></label></dd>
    <dt><?php echo $form['nueva_clave2'] ?></dt>
    <dd><label></label></dd>
    <dt><input type="submit" value="Guardar" class="button"/></dt>
</dl>
<div style="clear: both"></div>
<?php echo $form->close() ?>