<style type="text/css">
    body {
        font-family: tahoma, verdana, arial, sans-serif;
        font-size: 12px;
    }

    #novedades {
        border: 1px solid #ccc;
        width: 251px;
        height: 80px;
        overflow: hidden;
        left: -20px;
        top: -10px;
        padding: 8px 2px 2px 2px;
    }

    #novedades ul {
        margin: 0;
        padding: 0;
        position: relative;
        top: 0;
        left: 0;
    }

    #novedades li {
        margin: 0 0 20px 0;
        padding: 5px;
        height: 50px;
        /*overflow: hidden;*/
        line-height: 16px;
    }

    #novedades li a {
        font-weight: bold;
        text-transform: uppercase;
    }
</style>
<article class="col2 pad_left1">
    <div id="" style="width:215px;">
        <h2><span><span><strong>&nbsp;</strong>Noticias Calientes!!!</span></span></h2>
    </div>
    <div id="novedades" class="box1">
        <ul>
            <li><strong class="color1">06-12-2012</strong><br>Acuaman recibió un regalo en la poceta del baño de hombres...<a href="#" class="marker">&nbsp;</a></li>
            <li><strong class="color1">06-12-2012</strong><br>Hasta donde se conoce, ningún otro super amigo ha recibido regalito...<a href="#" class="marker">&nbsp;</a></li>
            <li><strong class="color1">06-12-2012</strong><br>Sugerencias: Hay super amigos y amigas que esperan un camburcito para hoy...<a href="#" class="marker">&nbsp;</a></li>
            <li><strong class="color1">06-12-2012</strong><br>Estén pendientes de los últimos avances en materia de los Super Amigos...<a href="#" class="marker">&nbsp;</a></li>
        </ul>
    </div>
</article>
<a href="#" id="banner1"><?php echo Html::img('banner1.jpg') ?></a>