<?php
    use Index\Model\Noticias;
    Noticias::createQuery()->order('id DESC');
    $noti = Noticias::findAll();
?>
<style type="text/css">
    body {
        font-family: tahoma, verdana, arial, sans-serif;
        font-size: 12px;
    }

    #novedades {
        border: 1px solid #ccc;
        width: 251px;
        height: 80px;
        overflow: hidden;
        left: -20px;
        top: -10px;
        padding: 8px 2px 2px 2px;
    }

    #novedades ul {
        margin: 0;
        padding: 0;
        position: relative;
        top: 0;
        left: 0;
    }

    #novedades li {
        margin: 0 0 20px 0;
        padding: 5px;
        height: 50px;
        /*overflow: hidden;*/
        line-height: 16px;
    }

    #novedades li a {
        font-weight: bold;
        text-transform: uppercase;
    }
</style>
<article class="col2 pad_left1">
    <div id="" style="width:215px;">
        <h2><span><span><strong>&nbsp;</strong>Noticias Calientes!!!</span></span></h2>
    </div>
    <div id="novedades" class="box1">
        <ul class="noti">
            <?php foreach($noti as $n){ ?>
                <li>
                    <strong class="color1">
                        <?php echo $n->hora; ?>
                    </strong>
                    <br>
                    <?php echo $n->noticia; ?>
                    <a href="#" class="marker">&nbsp;</a>
                </li>
            <?php } ?>
        </ul>
    </div>
    <h3><span><span><strong>&nbsp;</strong><?php echo Html::link('noticias/crear_noticia','Mete tu Chisme aqui...'); ?></span></span></h3>

</article>
<a href="#" id="banner1"><?php echo Html::img('banner1.jpg') ?></a>
<script>
    setInterval(actualiza, 30000);
    function actualiza(){
        location.reload();
    }
//    function actualiza(){
//        $.getJSON(BASE_URL + 'noticias/recargar', function(data){
//            var html = "";
//            $.each(data, function(){
//                html += "<li><strong class='color1'>"+this.hora+"</strong><br>"+this.noticia+"<a href='#' class='marker'>&nbsp;</a></li>";
//            });
//            console.log(html);
//            $(".noti").html(html);
//            $("#novedades").dwdinanews();
//        });
//    }
</script>