<div class="box1">
    <h2><span><span><strong>&nbsp;</strong>Latest News</span></span></h2>
    <p><strong class="color1">08.12.2010</strong><br>Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.<a href="#" class="marker">&nbsp;</a></p>
    <p><strong class="color1">03.12.2010</strong><br>Deleniti atque corrupti quos dolores quas molestias excepturi sint oaecati cupiditate provident.<a href="#" class="marker">&nbsp;</a></p>
    <p><strong class="color1">29.11.2010</strong><br>Similique sunt in culpa qui officia deserunt mollitia animi, iest laborum et dolorum dignissimos fuga.<a href="#" class="marker">&nbsp;</a> </p>
    <div class="centrer pad_bot2"><a href="#" class="button"><span><span>News Archive</span></span></a></div>
</div>
<a href="#" id="banner1"><?php echo Html::img('banner1.jpg') ?></a>