<header>
    <div class="wrapper" style="visibility: hidden">
        <form id="search" action="" method="post">
            <div>
<!--                <a href="#" class="button" onClick="document.getElementById('search').submit()"><span><span>Search</span></span></a>-->
<!--                <input type="text" class="input">-->
            </div>
        </form>
        <ul id="icons">
            <li><a href="#"><?php echo Html::img('icon1.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon2.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon3.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon4.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon5.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon6.gif') ?></a></li>
        </ul>
    </div>
    <div class="wrapper">
        <div id="banner">
            <h1><a href="index.html" id="logo">Merry X-Mas</a></h1>
            <?php if (!\KumbiaPHP\View\View::get('security')->isLogged()): ?>
                <span class="text">Si no tienes un personaje Asignado</span></span>
                <?php echo Html::link('registro', '<span><span>Has click Aqui</span>', 'class="button"') ?>
            <?php else: ?>
                <?php \KumbiaPHP\View\View::partial('personajes') ?>
            <?php endif; ?>
        </div>
    </div>
    <div id="menu">
        <div id="menu_left">
            <div id="menu_right">
                <nav>
                    <ul>
                        <li><?php echo Html::link('index', 'Inicio')?></li>
                        <li><?php echo Html::link('chat', 'Chat')?></li>
                        <li><?php echo Html::link('regalos', 'Regista tu regalo')?></li>
                        <li><?php echo Html::link('logout', 'Listado de Regalos')?></li>
                        <li><?php echo Html::link('logout', 'Cerrar Sesion')?></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
