<header>
    <div class="wrapper">
        <form id="search" action="" method="post">
            <div>
                <a href="#" class="button" onClick="document.getElementById('search').submit()"><span><span>Search</span></span></a>
                <input type="text" class="input">
            </div>
        </form>
        <ul id="icons">
            <li><a href="#"><?php echo Html::img('icon1.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon2.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon3.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon4.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon5.gif') ?></a></li>
            <li><a href="#"><?php echo Html::img('icon6.gif') ?></a></li>
        </ul>
    </div>
    <div class="wrapper">
        <div id="banner">
            <h1><a href="index.html" id="logo">Merry X-Mas</a></h1>
            <span class="text">Si no tienes un personaje Asignado</span></span>
            <?php echo Html::link('registro', '<span><span>Has click Aqui</span>','class="button"') ?>
        </div>
    </div>
    <div id="menu">
        <div id="menu_left">
            <div id="menu_right">
                <nav>
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="About.html">About</a></li>
                        <li><a href="Links.html">Links</a></li>
                        <li><a href="Contacts.html">Contacts</a></li>
                        <li class="bg_none"><a href="Sitemap.html">Sitemap</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>