<?php

$peronsajes = \Index\Model\Usuarios::findAll('array');
?>
<ul class="header_personajes">    
<?php foreach ($peronsajes as $e): ?>
    <li><?php echo Html::img($e['imagen'], $e['personaje']) ?></li>
<?php endforeach; ?>
</ul>
<style>
    .header_personajes{margin: 25px 0 0 0;padding: 0px;list-style: none;white-space: nowrap}
    .header_personajes li{float: right;margin: 5px;white-space: nowrap}
    .header_personajes li img{width: 35px;border-radius: 5px}
</style>