<!DOCTYPE html>
<html lang="en">
<head>
<title>Contacts</title>
<meta charset="utf-8">
<link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
<link rel="stylesheet" href="css/layout.css" type="text/css" media="all">
<link rel="stylesheet" href="css/style.css" type="text/css" media="all">
<script type="text/javascript" src="js/jquery-1.4.2.js" ></script>
<script type="text/javascript" src="js/cufon-yui.js"></script>
<script type="text/javascript" src="js/cufon-replace.js"></script>
<script type="text/javascript" src="js/UkrainianMysl_400.font.js"></script>
<script type="text/javascript" src="js/HomewardBound_400.font.js"></script>
<!--[if lt IE 9]>
<script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
<script type="text/javascript" src="js/html5.js"></script>
<![endif]-->
</head>
<body id="page4">
<div class="main">
<!-- header -->
	<header>
		<div class="wrapper">
			<form id="search" action="" method="post">
				<div>
					<a href="#" class="button" onClick="document.getElementById('search').submit()"><span><span>Search</span></span></a>
					<input type="text" class="input">
				</div>
			</form>
			<ul id="icons">
				<li><a href="#"><img src="images/icon1.gif" alt=""></a></li>
				<li><a href="#"><img src="images/icon2.gif" alt=""></a></li>
				<li><a href="#"><img src="images/icon3.gif" alt=""></a></li>
				<li><a href="#"><img src="images/icon4.gif" alt=""></a></li>
				<li><a href="#"><img src="images/icon5.gif" alt=""></a></li>
				<li><a href="#"><img src="images/icon6.gif" alt=""></a></li>
			</ul>
		</div>
		<div class="wrapper">
			<div id="banner">
				<h1><a href="index.html" id="logo">Merry X-Mas</a></h1>
				<span class="text">Create the Holiday Dreams <span>And Keep Your Spirits High!</span></span>
				<a href="#" class="button"><span><span>Click Here</span></span></a>
			</div>
		</div>
		<div id="menu">
			<div id="menu_left">
				<div id="menu_right">
					<nav>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="About.html">About</a></li>
							<li><a href="Links.html">Links</a></li>
							<li><a href="Contacts.html">Contacts</a></li>
							<li class="bg_none"><a href="Sitemap.html">Sitemap</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
<!-- / header -->
<!--content -->
	<section id="content">
		<article class="col1">
			<div class="box1 min_height">
				<h3><span><span><strong>&nbsp;</strong>Contact Form</span></span></h3>
				<form id="ContactForm" action="">
					<div>
						<div class="wrapper"><input type="text" class="input" /><strong>Name:</strong><br /></div>
						<div class="wrapper"><input type="text" class="input" /><strong>Email:</strong><br /></div>
						<div class="wrapper"><textarea name="textarea" cols="1" rows="1"></textarea><strong>Message:</strong><br /></div>
						<div class="centrer">
							<a href="#" class="button" onClick="document.getElementById('ContactForm').reset()"><span><span>clear</span></span></a>
							<a href="#" class="button" onClick="document.getElementById('ContactForm').submit()"><span><span>send</span></span></a>
						</div>
					</div>
				</form>
			</div>
 </article>
		<article class="col2 pad_left1">
			<div class="box1">
				<h2><span><span><strong>&nbsp;</strong>Latest News</span></span></h2>
				<p><strong class="color1">08.12.2010</strong><br>Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.<a href="#" class="marker">&nbsp;</a></p>
				<p><strong class="color1">03.12.2010</strong><br>Deleniti atque corrupti quos dolores quas molestias excepturi sint oaecati cupiditate provident.<a href="#" class="marker">&nbsp;</a></p>
				<p><strong class="color1">29.11.2010</strong><br>Similique sunt in culpa qui officia deserunt mollitia animi, iest laborum et dolorum dignissimos fuga.<a href="#" class="marker">&nbsp;</a></p>
				<div class="centrer pad_bot2"><a href="#" class="button"><span><span>News Archive</span></span></a></div>
			</div>
			<a href="#" id="banner1"><img src="images/banner1.jpg" alt=""></a>
 </article>
	</section>
<!-- / content -->
<!-- footer -->
	<footer>
		Website template designed by <a href="http://www.templatemonster.com/" target="_blank" rel="nofollow">www.templatemonster.com</a><br>
		3D Models provided by <a href="http://www.templates.com/product/3d-models/" target="_blank" rel="nofollow">www.templates.com</a>
	</footer>
<!-- / footer -->
</div>
<script type="text/javascript"> Cufon.now(); </script>
</body>
</html>