<?php \KumbiaPHP\View\View::content(true) ?>
<h3><span><span><strong>&nbsp;</strong>Merry Christmas and Happy New Year!</span></span></h3>
<div class="wrapper">
    <figure class="left marg_right1"><?php echo Html::img('page1_img1.jpg') ?></figure>
    <p class="pad_bot1"><strong>Et harum quidem rerum facilis est et expedita distinctio</strong></p>
    <p>Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit minus id quod maxime placeat facere possimus, omnis <a href="#">voluptas assumenda</a> est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerumsaepe eveniet ut et voluptates repudiandae sint et molestiae recusandae. </p>
</div>
<div class="wrapper line1 marg_bot1">
    <ul class="list1 cols">
        <li><a href="#">Sed ut perspiciatis unde omnis iste natus error</a></li>
        <li><a href="#">Voluptatem accusantium doloremque</a></li>
        <li><a href="#">Laudantium, totam rem aperiam, eaque ipsaiuae</a></li>
        <li><a href="#">Abillo inventore veritatis etquasrchto beatae</a></li>
    </ul>
    <ul class="list1 cols pad_left2">
        <li><a href="#">Vitae dicta sunt explicabo. Nemo enim</a></li>
        <li><a href="#">Ipsam voluptatem quia voluptas sit aspernatur</a></li>
        <li><a href="#">Aut odit aut fugi quia consequuntur magni dolore</a></li>
        <li><a href="#">Eos qui ratione voluptatem sequi nesciunt</a></li>
    </ul>
</div>
<h3><span><span><strong>&nbsp;</strong>New Ideas for Celebration</span></span></h3>
<p class="pad_bot1">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae:</p>
<ul class="list2 pad_bot2">
    <li><a href="#">Vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur </a></li>
    <li><a href="#">Aut odit aut fugit, sed quia consequuntur magni dolores eos qui </a></li>
    <li><a href="#">Ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem </a></li>
    <li><a href="#">Ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora</a></li>
</ul>
